### PR TITLE
Ajc/create video

### PR DESCRIPTION
**Pull request by jonmatthis**
[Copied from the PR I accidentally opened on the `freemocap_tools` repo 😅 ]

Hey @ajc27-git - I'm finally getting a chance to look at your work!

I'm opening this PR myself because I remember you said this was working. Going forward, when you are ready for me to look at a branch, you can open a PR onto the main branch.

The code does not need to be ready to merge when you open a PR!

You can open it as soon as you like, and we can discuss the changes on the PR page :)

### CODE REVIEW

**Comment by jonmatthis** [comment]
I was able to get it running up the point of generating the video (before the overlays)

https://github.com/user-attachments/assets/4387e7aa-18b6-4d5b-9614-815c0ef99a1a

It looks good so far! 


...but fails at: 

```
  File "C:\Users\jonma\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ajc27_freemocap_blender_addon\core_functions\create_video\create_video.py", line 461, in add_visual_components
    height=EXPORT_PROFILES[export_profile]['resolution_y'],
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'logo'
```
We need to clean up the use of `globals()` in various places - it's not recommended to use `globals()`, as it leads to problems like this :) @philipqueen can help find alternative methods when he gets back from his trips

A few notes: 

- Please use PEP8 naming for your classes - I think you're using `snake_case` for everything, but Classes are supposed to be `PascalCase` and their instances are `snake_case` (e.g. `my_class = MyClass()`) 

- Would be nice to remove the `cv2` dependency - the 🤖  says we can use something like `bpy.scene.sequence_editor_create()` to make the overlays, but I haven't tried it

- We should add a groundplane along with the scene lights/cameras/etc - its traditional to have the ground plane be a grid of muted alternating colors, with the squares a reasonable unit ratio, like 0.1 m (or whatever looks nice)

**Comment by jonmatthis** [comment]
Just tested the botto's code, it does successfully make a video overlay and save it out!

Example script here - https://github.com/freemocap/freemocap_blender_addon/blob/ajc/create_video/experiments/video_overlay.py

we can try to adapt this for our purposes here :)

**Comment by ajc27-git** [comment]
@jonmatthis the use of globals was to save lines of code to initialize the different video overlays elements as they have the same constructor and the classes are named equal to the overlay element. A simple way to avoid that is to add if to get what element if being added and execute the corresponding class constructor.
The other important thing is that you merged the other ajc addon repository main branch into this branch. Most probably that will generate conflict if this is merge to the official addon.

image

**Comment by philipqueen** [comment]
It looks like Jon merged form upstream instead of origin. Unfortunately, undoing a big merge in git is non trivial (`git revert` has some odd behavior here, see: https://opensource.apple.com/source/Git/Git-26/src/git-htmldocs/howto/revert-a-faulty-merge.txt). Try to `reset` the branch to the commit before the merge only seemed to undo some changes, but still left ~14,000 lines of unwanted code. @ajc27-git had all of the work in his local branch still, so he made a new branch found in PR #15. I've copied all of the comments from here to there, and am closing this PR

**Pull request closed without merging**
